-- Test copy of the gateway's schema contract (tables reduced to what the views need). Keep the four views
-- identical to Fairness-Checker/src/main/resources/db/migration V2 + V3.
DROP VIEW IF EXISTS scoring_oncall_v, scoring_assignment_v, scoring_alert_v, scoring_engineer_v;
DROP TABLE IF EXISTS oncall_shift, alert_assignment, alert_event, engineer_data, team;

CREATE TABLE team (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL UNIQUE,
    timezone VARCHAR(64)  NOT NULL DEFAULT 'Asia/Kolkata'
);

CREATE TABLE engineer_data (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   VARCHAR(255) NOT NULL,
    name    VARCHAR(255) NOT NULL,
    team_id BIGINT       NOT NULL REFERENCES team (id),
    active  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE alert_event (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pager_duty_incident_id VARCHAR(255) UNIQUE,
    severity               VARCHAR(255),
    status                 VARCHAR(255) NOT NULL DEFAULT 'triggered',
    triggered_at           TIMESTAMP(6) NOT NULL,
    acknowledged_at        TIMESTAMP(6),
    resolved_at            TIMESTAMP(6),
    engineer_id            BIGINT REFERENCES engineer_data (id)
);

CREATE TABLE alert_assignment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id    BIGINT       NOT NULL REFERENCES alert_event (id),
    engineer_id BIGINT REFERENCES engineer_data (id),
    kind        VARCHAR(16)  NOT NULL,
    assigned_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE oncall_shift (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engineer_id      BIGINT       NOT NULL REFERENCES engineer_data (id),
    escalation_level SMALLINT     NOT NULL DEFAULT 1,
    starts_at        TIMESTAMP(6) NOT NULL,
    ends_at          TIMESTAMP(6) NOT NULL
);

CREATE VIEW scoring_engineer_v AS
SELECT e.id AS engineer_id, e.name, t.name AS team, e.active, t.id AS team_id, t.timezone
FROM engineer_data e
         JOIN team t ON t.id = e.team_id;

CREATE VIEW scoring_alert_v AS
SELECT a.id                                                  AS alert_id,
       a.engineer_id,
       a.severity,
       a.status,
       a.triggered_at,
       a.resolved_at,
       a.acknowledged_at,
       (a.triggered_at AT TIME ZONE 'UTC') AT TIME ZONE t.timezone AS triggered_at_local,
       (SELECT count(*)
        FROM alert_assignment x
        WHERE x.alert_id = a.id AND x.kind = 'ESCALATED')    AS escalation_count
FROM alert_event a
         JOIN engineer_data e ON e.id = a.engineer_id
         JOIN team t ON t.id = e.team_id
WHERE a.engineer_id IS NOT NULL;

CREATE VIEW scoring_assignment_v AS
SELECT x.alert_id, x.engineer_id, x.kind, x.assigned_at
FROM alert_assignment x
WHERE x.engineer_id IS NOT NULL
  AND x.kind IN ('ESCALATED', 'REASSIGNED');

CREATE VIEW scoring_oncall_v AS
SELECT engineer_id, escalation_level, starts_at, ends_at
FROM oncall_shift;
